### ISSUE TITLE
Cannot complete php artisan membership:install

### ISSUE THREAD

**Issue by simonwinter** [atorscho/membership#2]
When running `php artisan membership:install`, we get the follwoing error:

[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: alter table `user_groups` add constrain
  t `user_groups_user_id_foreign` foreign key (`user_id`) references `` (`id`) on delete cascade)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

This is due to the reliance on `config('auth.table')` which does not exist in laravel 5.

**Comment by atorscho** [comment]
Thank you for your feedback.

I will fix this bug in the very next release.
