### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by mathisloge** [atorscho/membership#4]
[https://atorscho.gitbooks.io/membership/content/docs/installation.html](https://atorscho.gitbooks.io/membership/content/docs/installation.html) 

> Page Not Found
The book published at this address does not contain the requested page.
It may have been moved or deleted by its author.

**Comment by atorscho** [comment]
Sorry, it is due to the development process. I have almost finished the v2 with a new and clearer documentation.

**Comment by atorscho** [comment]
@mathisloge, I am currently adding a [new documentation](https://github.com/atorscho/membership/wiki) for the 2nd version of the package, in case you are interested.

> Currently in progress as of 15 Aug 2017
